In [1]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go

In [2]:
commercial = pd.read_csv('Commercial.csv')
commercial.head()

,Company,HQ Location,Constellation,Sensor Moda,Update,Pan,VNIR 400-1K nm,Unnamed: 7,Unnamed: 8,LWIR 8K-12K nm,...,Band Width (nm) MWIR,Band Width (nm) LWIR,Spectral Range (nm) VNIR.1,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36
0,LatConnect,Australia,LatConnect60,EO,NaN,0.5m<=x<=1m,1m<x<=5m,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SATLANTIS,US/Spain,SATLANTIS,EO,NaN,0.5m<=x<=1m,0.5m<=x<=1m,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Zhuhai,China,"Zhuhai-1 (OIS, OVS)",EO,NaN,0.5m<=x<=1m,NaN,NaN,NaN,5m<x<=30m,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Canon,Japan,CE-SAT,EO,NaN,NaN,0.5m<=x<=1m,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Theia,US,THEIA Satellite Network (TSN),EO,NaN,NaN,0.5m<=x<=1m,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
data = (commercial["Sensor Moda"] == "EO") & (commercial["Company"] == "LatConnect")
commercial[data]

,Company,HQ Location,Constellation,Sensor Moda,Update,Pan,VNIR 400-1K nm,Unnamed: 7,Unnamed: 8,LWIR 8K-12K nm,...,Band Width (nm) MWIR,Band Width (nm) LWIR,Spectral Range (nm) VNIR.1,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36
0,LatConnect,Australia,LatConnect60,EO,NaN,0.5m<=x<=1m,1m<x<=5m,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
#Create list of Companies
c_array = np.unique(commercial["Company"].to_numpy()) 
h_array = np.unique(commercial["HQ Location"].to_numpy())
print (c_array)

#Create unique list of Sensor Moda without &

def myFunc(string):
    if "&" in string:
        return False
    else:
        return True
s_array = np.unique(commercial["Sensor Moda"].to_numpy())
s_array_f = list(filter(myFunc, s_array))
s_array_f

['21at; SSTL' 'ADA Space' 'AISTech Space' 'Acme AtronOmatic'
 'Aerospacelab' 'Airbus' 'Airbus US' 'Airbus; Azercosmos' 'Aireon'
 'Alba Orbital' 'Albedo' 'Alpha Insights (Urthecast)' 'Astro Digital'
 'Astroscale' 'Aurora Insight' 'Austrian Space Forum (OeWF)' 'AxelSpace'
 'BlackSky Technology Inc' 'BlackSky Technology Inc.' 'Bluefield' 'CAS'
 'CETC' 'CNSA' 'Canadian Space Agency' 'Canon' 'Capella Space'
 'Chang Guang' 'ConstellR' 'DMCii; SSTL' 'Deimos Imaging;Urthecast'
 'Digantara' 'DragonFly; Space JLTZ' 'EOS' 'Earth - I'
 'Earth Observant (EOI)' 'EarthDaily Analytics' 'GHGSat Inc' 'GOMSpace'
 'Guardian Space Technology Solutions' 'HEAD Aerospace' 'HEO Robotics'
 'HKATG' 'Hancom InSpace' 'HawkEye 360' 'Hawkeye 360' 'Hera Systems'
 'Horizon Technologies' 'HySpecIQ LLC' 'Hydrosat' 'HyperSat LLC' 'Iceye'
 'ImageSat' 'ImageSat International (ISI)' 'Inovor' 'JAXA'
 'Jihua Laboratory' 'KARI' 'KP Labs' 'KSAT' 'Karten'
 'Kazakhstan Gharysh Sapary' 'Kineis' 'Kleos Space SA' 'Koolock'
 'Kuva Space' 'LatConnect' 'Live Earth Imaging' 'MDA'
 'Maxar (DigitalGlobe)' 'MethaneSAT, LLC' 'MinoSpace' 'Myriota' 'NEC'
 'Ningzia' 'NorthStar Earth & Space' 'OHB Italia' 'ORBCOMM'
 'Orbital Effects (R2 Space)' 'Orbital Sidekick' 'Orora Tech' 'PIESat'
 'Pixxel' 'Planet' 'Planet/JPL' 'PredaSAR' 'Qiansheng' 'Roscosmos'
 'SATLANTIS' 'SCOUT' 'SI Imaging Services' 'SSTL' 'ST Electronics'
 'ST Engineering' 'SatRevolution' 'Satellite Vu' 'Satellogic' 'Satrec'
 'Scanway' 'Sen' 'Shaanxi Zhixing Space Technology'
 'Shandong Institutes of Industrial Tech' 'Simera Group; ISISpace'
 'Skeyeon' 'Space View Technology' 'SpaceBel' 'SpaceFab'
 'SpaceView Technology' 'Spacety' 'Spire Global' 'Startical' 'Synspective'
 'Technion' 'Teledyne Brown' 'Theia' 'Trident Space' 'UAE; Airbus' 'Umbra'
 'Unseen Labs' 'Veoware Space' 'Virgin Orbit' 'Wyvern' 'XpressSAR'
 'ZeroG Lab' 'Zhuhai' 'eGEOS' 'exactEarth (Spire Global)' 'iQPS']

['EO', 'HSI', 'RF', 'SAR', 'SSA']

In [11]:
import tkinter

window=tkinter.Tk()

window.title('GUI Program')

window.geometry('500x200')

 

#Creating a dropdown list of the companies

 

company_label=tkinter.Label(window, text='Company Name:')

company_label.place(relx=.03, rely=.02)

 

company_options=c_array

 

company_inside=tkinter.StringVar(window)

company_inside.set('Select Company Name')

 

 

company_dropdown_list=tkinter.OptionMenu(window, company_inside, *company_options)

company_dropdown_list.place(relx=.03, rely=.05)

 

def print_Company():

    print('Company Selected: {}'.format(company_inside.get()))

    return str(company_inside.get())

 

 

 

 

#Operational Status radio buttons

 

hq_label=tkinter.Label(window, text='HQ Location:')

hq_label.place(relx=.15, rely=.02)

 

hq_options=h_array

 

hq_inside=tkinter.StringVar(window)

hq_inside.set('Select HQ Location')

 

 

hq_dropdown_list=tkinter.OptionMenu(window, hq_inside, *hq_options)
hq_dropdown_list.place(relx=.15, rely=.05)

 


 

def print_hq():

    print('Location Selected: {}'.format(hq_inside.get()))

    return str(hq_inside.get())

 

 

#Manual Entry Search by Satellite Name

name_label=tkinter.Label(window, text='Satellite Name:')

name_label.pack()

 

def print_name():

    print('Satellite Name is: ' + name_entry.get())

   

name_entry=tkinter.Entry(window)

name_entry.pack()

 

#Manual Entry Search by ID Number

ID_label=tkinter.Label(window, text='ID Number:')

ID_label.pack()

 

def print_ID():

    print('ID Number is: '+ID_entry.get())

   

ID_entry=tkinter.Entry(window)

ID_entry.pack()

 

#Check buttons in Python Satellite Constellation type

satellite_type_label=tkinter.Label(window, text='Satellite Type:')

satellite_type_label.place(relx=0.7, rely=0.02)


#Create buttons using for loop
#Proxy list to access tkinker.StringVar().get later on
count = 0
proxy = []
for var in s_array_f:
    satellite_type = tkinter.StringVar()
    proxy.append(satellite_type)
    button=tkinter.Checkbutton(window, text=var, variable=satellite_type, onvalue=var, offvalue='')
    button.place(relx=0.7, rely=0.04 + count * 0.02)
    count += 1


#Print out satellite types that are not None
def print_Sensor_Moda():
    proxy_2 = []
    for x in proxy:
        if x.get():
            print('Type Selected: {}'.format(x.get()))
            proxy_2.append(x.get())
    return " & ".join(proxy_2)
 



                             

#Submit Button

submit_button=tkinter.Button(window, text='Submit', command=lambda:[print_Company(),print_hq(),print_name(), print_ID(), print_Sensor_Moda()])

submit_button.place(relx=.03, rely=.35)

 

 

#Main loop

window.mainloop()

Company Selected: CNSA
Location Selected: China
Satellite Name is:
ID Number is:
Type Selected: EO

In [12]:
col = ["Company", "HQ Location", "Sensor Moda"]
fields = dict.fromkeys(col,0)
fields_1 = {"Company": "print_Company()" , "HQ Location": "print_hq()", "Sensor Moda": "print_Sensor_Moda()"}
def update (fields):
    if (len(print_Sensor_Moda()) != 0):
        fields["Sensor Moda"] = 1
    if print_Company() != "Select Company Name":
        fields["Company"] = 1
    if print_hq() != "Select HQ Location":
        fields["HQ Location"] = 1
update(fields)
# print(fields)


initial_filter = True
for key in fields.keys():
    if fields.get(key) == 1:
        filtered = initial_filter & (commercial[key] == eval(fields_1.get(key)))
        initial_filter = filtered
        

commercial[initial_filter]

Type Selected: EO
Company Selected: CNSA
Location Selected: China
Company Selected: CNSA
Location Selected: China
Type Selected: EO

,Company,HQ Location,Constellation,Sensor Moda,Update,Pan,VNIR 400-1K nm,Unnamed: 7,Unnamed: 8,LWIR 8K-12K nm,...,Band Width (nm) MWIR,Band Width (nm) LWIR,Spectral Range (nm) VNIR.1,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36
72,CNSA,China,GaoFen EO,EO,NaN,0.5m<=x<=1m,1m<x<=5m,NaN,>30m,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,CNSA,China,ZiYuan,EO,NaN,1m<x<=5m,5m<x<=30m,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN